### ISSUE TITLE
Would be nice to have sample output from example

### ISSUE THREAD

**Issue by Kri-Ol** [fangq/zmat#3]
Installation looks to be working with MATLAB 2014b, but when running example/demo_zmat_basic.m it would be nice if each command output would be dupl;icated such that user cold check at once if it is working or not

**Comment by fangq** [comment]
sorry, just saw this request submitted a while ago.

can you explain what do you mean by "each command output would be duplicated"? 

the demo script is already printing the output after each function call

https://github.com/fangq/zmat/blob/master/example/demo_zmat_basic.m
