### ISSUE TITLE
Honor environment variables CFLAGS, CPPFLAGS, and LDFLAGS

### ISSUE THREAD

**Issue by rlaboiss** [fangq/zmat#7]
The building of the zmat package ignores the setting of the environment variables CFLAGS, CPPFLAGS, and LDFLAGS.

We are currently applying a [patch](https://salsa.debian.org/pkg-octave-team/zmat/-/blob/debian/latest/debian/patches/honor-cflags-cppflags-ldflags.patch) to the Debian package zmat that fixes the problem. This allows the inclusion of [hardening flags](https://wiki.debian.org/Hardening) like -D_FORTIFY_SOURCE=2, -fstack-protector-strong, -Wformat, -Werror=format-security, and -Wl,-z,relro.

**Comment by fangq** [comment]
hi Rafael, so glad to hear from you. yes, I meant to back port those patches for the next release, thanks for reminding, should be fixed now.
